export type ProductEntry = {
  id: number
  name: string
  description: string
  price: number
  categories: Category[]
  categoriesIds: number[]
  defaultDisplayedPriceFormatted: string
  thumbnailUrl: string
  imageUrl: string
  galleryImages: GalleryImage[]
  defaultCategoryId: number
  createTimestamp: number
  seoDescription: string
  seoTitle: string
  media: ProductMedia
}

type ProductMedia = {
  images: ProductImage[]
  videos: ProductVideo[]
}

type ProductImage = {
  id: string
  alt: { main: string }
  orderBy: number
  isMain: boolean
  image160pxUrl: string
  image400pxUrl: string
  image800pxUrl: string
  image1500pxUrl: string
  imageOriginalUrl: string
}
type ProductVideo = {
  //
}

type GalleryImage = {
  id: number
  url: string
  thumbnail: string
  originalImageUrl: string
  imageUrl: string
  hdThumbnailUrl: string
  thumbnailUrl: string
  smallThumbnailUrl: string
  width: number
  height: number
  orderBy: number
}

export type ImageDetails = {
  url: string
  width: number
  height: number
}

export type Category = {
  id: number
  parentId: number
  orderBy: number
  hdThumbnailUrl: string
  thumbnailUrl: string
  imageUrl: string
  originalImageUrl: string
  originalImage: ImageDetails
  name: string
  thumbnail: ImageDetails
  nameTranslated: string
  origin: string
  url: string
  autogeneratedSlug: string
  customSlug: string
  productCount: number
  enabledProductCount: number
  description: string
  descriptionTranslated: string
  enabled: boolean
  productIds: number[]
  seoTitle: string
  seoTitleTranslated: string
  seoDescription: string
  seoDecriptionTranslated: string
  alt: string
}
